name: Python checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    name: Lints
    runs-on: ubuntu-latest

    steps:
    - name: Check out MNI 7T BIDS converter
      uses: actions/checkout@v4

    - name: Install MNI 7T BIDS converter
      uses: ./.github/actions/install-project

    - name: Run Ruff
      run: ruff check --output-format=github

  pyright:
    name: Type checks
    runs-on: ubuntu-latest

    steps:
    - name: Check out MNI 7T BIDS converter
      uses: actions/checkout@v4

    - name: Install MNI 7T BIDS converter
      uses: ./.github/actions/install-project

    # The `jq` arcane is used to translate the errors from JSON to the GitHub actions format
    - name: Run Pyright
      run: |
        pyright --outputjson | jq -r '.generalDiagnostics[] | "::error file=\(.file),line=\(.range.start.line),col=\(.range.start.character)::\(.message)"'
        (exit ${PIPESTATUS[0]})
